### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by whmountains** [HubSpot/offline#253]
It would be really nice!

**Comment by FranDias** [comment]
@geekjuice Anything special with that?

**Comment by whmountains** [comment]
Just add a `package.json` and then define module.exports if you detect a commonjs environment.

**Comment by whmountains** [comment]
Here's an example of the type of logic that's required:

https://github.com/kriskowal/q/blob/master/q.js

**Comment by also** [comment]
Hey @whmountains, offline is published to npm as [`offline-js`](https://www.npmjs.com/package/offline-js). The recent language updates haven't been published yet, and we'll get to that soon. Otherwise, the way we publish the package isn't going to change, as we aren't maintaining this project any more.

**Comment by also** [comment]
I've published [v0.7.19](https://github.com/HubSpot/offline/releases/tag/v0.7.19) to npm.

https://www.npmjs.com/package/offline-js
